### ISSUE TITLE
[ide] Multi-level catalog causes ROM overflow

### ISSUE THREAD

**Issue by qiaojingx** [intel/zephyr.js#1545]
### Description

If the path of `zephyr.js` is long, `make ide ROM=256` will cause ROM overflow. 
 
### Test Code

[ashell.md](https://github.com/01org/zephyr.js/blob/master/docs/ashell.md)
 
### Steps to Reproduction

1.  Create folder with multil-evel catalog like: `/home/neusoft/aaaaaa/bbbbbb/cccccc/dddddd/`
2.  Try to build `ide` in `zephyr.js` which is placed under these catalogs.

### Actual Result

 If the path is `/home/neusoft/aaaaaa/bbbbbb/zephyr.js`, `make ide ROM=256` will get error:
![selection_007](https://user-images.githubusercontent.com/19813546/30633460-4aafb000-9e1e-11e7-86ff-384108fd82b6.png)

 If the path is `/home/neusoft/aaaaaa/bbbbbb/cccccc/zephyr.js`, `make ide ROM=256` will get error:
![selection_008](https://user-images.githubusercontent.com/19813546/30633488-608557c2-9e1e-11e7-896d-c410c2af5651.png)

### Expected Result

The path of zephyr.js doesn't affect ide building.
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 174f35f | Arduino 101 | Sep, 20, 17 | Fail
zjs-0.4 | b11dc55 | Arduino 101 | Sep, 20, 17 | Fail
 
### Additional Information

Test with latest commit 151a2ae. `make ide ROM=256` will get RAM overflow and `make ide ROM=255` will get ROM overflow if the path of `zephyr.js` is `/home/neusoft/aaaaaa/bbbbbb/cccccc/dddddd/eeeeee/ffffff/jjjjjj/hhhhhh/iiiiii/zephyr.js`

**Comment by brianjjones** [comment]
@grgustaf I'm pretty sure this a build issue, any chance you know off hand what the problem is?  This isn't related directly to IDE other than the fact that it pulls in all the modules, using up more memory.

**Comment by grgustaf** [comment]
This is because we use __file__ macro so the big long path of each file gets stored in the binary. @nagineni fixed it I think, by disabling that __file__ usage except for debug builds.

@qiaojingx can you check the latest?

**Comment by qiaojingx** [comment]
Verified with commit cbec79d in master, this issue is fixed. But it still exists in zjs-0.4 branch. 
Will the zjs-0.4 branch be fixed, too?

**Comment by grgustaf** [comment]
No, let's not worry about it for 0.4 at this point. We'll be releasing 0.5 soon.
