### ISSUE TITLE
[docs] The k64f_pins.md doc need to update

### ISSUE THREAD

**Issue by cuiyanx** [intel/zephyr.js#1663]
### Description

We support AIO and PWM APIs to K64f board, but [/docs/k64f_pins.md](https://github.com/01org/zephyr.js/blob/master/docs/k64f_pins.md) doc has not be updated.
So, please do it.
 
```
    attribute unsigned long PWM0;
    attribute unsigned long PWM1;
    attribute unsigned long PWM2;
    attribute unsigned long PWM3;
    attribute unsigned long PWM4;
    attribute unsigned long PWM5;
    attribute unsigned long PWM6;
    attribute unsigned long PWM7;
    attribute unsigned long PWM8;
    attribute unsigned long PWM9;

    attribute unsigned long A0;
    attribute unsigned long A1;
    attribute unsigned long A2;
    attribute unsigned long A3;
    attribute unsigned long A4;
    attribute unsigned long A5;
```
```
PWM Pins

The FRDM-K64F has ten pins that can be used as PWM output, PWM0 - PWM9. These are defined but support has not been added yet.

AIO Pins

The FRDM-K64F has six analog input pins, A0 - A5. These are defined but support has not been added yet.
```

### Test Code

[/docs/k64f_pins.md](https://github.com/01org/zephyr.js/blob/master/docs/k64f_pins.md)

 

### Actual Result

No update.
 

### Expected Result

 update

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | dcf56a9 | FRDM-K64F | Nov 16, 2017 | Fail

**Comment by grgustaf** [comment]
This file has been eliminated along the module it documented; closing.

**Comment by cuiyanx** [comment]
Yeah, closed.
