### ISSUE TITLE
[timers] BUS fault error occurs when running test-timers.js on 96b_carbon/stm32f4_disco/olimex_stm32_e407

### ISSUE THREAD

**Issue by qiaojingx** [intel/zephyr.js#1686]
### Description

test-timers.js will cause bus fault error on boards: 96b_carbon, stm32f4_disco and olimex_stm32_e407
 
### Test Code

[test-timers.js](https://github.com/01org/zephyr.js/blob/master/tests/test-timers.js)
 
### Steps to Reproduction

96b_carbon:
1. `make BOARD=96b_carbon JS=tests/test-timers.js`
2. `dfu-util -a 0 -d 0483:df11 -D outdir/96b_carbon/zephyr.bin --dfuse-address 0x08000000`

stm32f4_disco:
1. `make BOARD=stm32f4_disco JS=tests/test-timers.js`
2. `cp outdir/stm32f4_disco/zephyr.bin /media/<username>/DIS_F407VG/`

olimex_stm32_e407:
1. `make BOARD=olimex_stm32_e407 JS=tests/test-timers.js`
2. `dfu-util -a 0 -d 0483:df11 -D outdir/olimex_stm32_e407/zephyr.bin --dfuse-address 0x08000000`
### Actual Result

![selection_006](https://user-images.githubusercontent.com/19813546/33538102-5d4c905e-d8fa-11e7-97a5-3f2e340697f8.png)
 
### Expected Result

 
![selection_007](https://user-images.githubusercontent.com/19813546/33538112-675e4c7c-d8fa-11e7-8577-26aabc7f8881.png)

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | cbec79d | 96Boards Carbon | Dec 4, 2017 | Fail
master | cbec79d | STM32F4DISCOVERY | Dec 4, 2017 | Fail
master | cbec79d | OLIMEX-STM32-E407 | Dec 4, 2017 | Fail

**Comment by jimmy-huang** [comment]
@qiaojingx can you post the lines of code that it is crashing by searching the instruction address: 8001d72 in the outdir/$BOARD/zephyr/zephyr.lst file.  I've tried reproducing on the 96b_carbon, but not able to, we'll try to reproduce it on other boards as well.

**Comment by jimmy-huang** [comment]
I can reproduce this with the old cbec79d commit with Zephyr 1.9, but I can't reproduce this on the olimex_stm32_e407 or 96b_carbon with the latest master with Zephyr 1.10, so I think this issue is fixed with 1.10, please re-test.

**Comment by qiaojingx** [comment]
Verified with commit 8b0ac4d. This issue is fixed.
Close
