### ISSUE TITLE
CMake version race

### ISSUE THREAD

**Issue by pfalcon** [intel/zephyr.js#1706]
Trying to build the latest master:

~~~
CMake Error at CMakeLists.txt:3 (cmake_minimum_required):
  CMake 3.9 or higher is required.  You are running version 3.8.2
~~~

Really? Can't you guys stick with the version which Zephyr requires, which is 3.8.2, and which is not available as a native package for many Linux distros, so require additional pain on the user to install?

**Comment by qiaojingx** [comment]
Verified with commit b32969f. This issue is not reproduced.
