### ISSUE TITLE
[ocf] Cannot create multiple resources

### ISSUE THREAD

**Issue by qiaojingx** [intel/zephyr.js#1707]
### Description

Error `512:(ERROR) failed to create new resource` will occurs when running ocfserver which has multiple resources.

### Test Code

[OcfMultiSensor.js](https://github.com/01org/zephyr.js/blob/master/samples/OcfMultiSensor.js);
[th02-ocf.js](https://github.com/01org/zephyr.js/tree/master/samples/thermostat/th02-ocf.js);
[test-ocfserver.js](https://github.com/01org/zephyr.js/blob/master/tests/test-ocfserver.js);
 
### Steps to Reproduction

1. `make JS=tests/test-ocfserver.js ROM=256`
2. `make dfu`
 
### Actual Result

![selection_020](https://user-images.githubusercontent.com/19813546/33927292-a36d217e-e01c-11e7-8ba2-0d89cb57bf9a.png)

 
### Expected Result

Each resource can be created without error.
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 1b970c8 | Arduino 101 | Dec 13, 2017 | Fail
master | 1b970c8 | FRDM-K64F | Dec 13, 2017 | Fail

**Comment by jimmy-huang** [comment]
This is related to RAM issue on the Arduino101, is this reproducible on the 96b_carbon?

**Comment by qiaojingx** [comment]
@jimmy-huang , Ocf cannot be built for 96b_carbon.
Does ocf moudle is supported on 96b_carbon(ble) and OLIMEX STM32 E407(Ethernet)? If so, I need create issues for them.

**Comment by jimmy-huang** [comment]
Yeah, it probably make sense to create issues, since they should work, we probably just need to update the json files to add the board for it to compile.

**Comment by qiaojingx** [comment]
Ocf issue on 96b_carbon is tracking by #1771 and ocf issue on OLIMEX STM32 E407 is tracking by #1772 .

**Comment by jimmy-huang** [comment]
patch submitted #1785, please retest.

**Comment by cuiyanx** [comment]
Verified with commit f51fcc3b02 on master.

| | A101 | K64f | 96b |
| :----: | :----: | :----: | :----: |
| [test-ocfserver.js](https://github.com/intel/zephyr.js/blob/master/tests/test-ocfserver.js) | Fail | Fail | Fail |
| [OcfMultiSensor.js](https://github.com/intel/zephyr.js/blob/master/samples/OcfMultiSensor.js) | Fail | Fail | Not Support AIO |
