### ISSUE TITLE
[tcp] Stack Check Fail in qemu

### ISSUE THREAD

**Issue by qiaojingx** [intel/zephyr.js#1711]
### Description

When running [test-tcp6-server.js](https://github.com/01org/zephyr.js/blob/master/tests/test-tcp6-server.js), [test-tcp4-server.js](https://github.com/01org/zephyr.js/blob/master/tests/test-tcp4-server.js) and [test-tcp4-server-DHCP.js](https://github.com/01org/zephyr.js/blob/master/tests/test-tcp4-server-DHCP.js) in qemu, `Stack Check Fail` will occur. But not reproduce on A101 and K64F.

### Test Code

[test-tcp6-server.js](https://github.com/01org/zephyr.js/blob/master/tests/test-tcp6-server.js);
[test-tcp4-server.js](https://github.com/01org/zephyr.js/blob/master/tests/test-tcp4-server.js); 
[test-tcp4-server-DHCP.js](https://github.com/01org/zephyr.js/blob/master/tests/test-tcp4-server-DHCP.js);

### Steps to Reproduction

 1. Start net-tools on Linux:
terminal 1: ` ./loop-socat.sh`
terminal 2: `sudo ./loop-slip-tap.sh`
 2. `make JS=tests/test-tcp6-server.js ROM=256 BOARD=qemu_x86 qemu`

### Actual Result

![selection_014](https://user-images.githubusercontent.com/19813546/33928557-3fe01080-e021-11e7-8cc7-c73527de56dd.jpg)

### Expected Result

No error occurs
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 1b970c8 | QEMU | Dec 13, 2017 | Fail

**Comment by grgustaf** [comment]
Fixed in #1776. However I wasn't able to reproduce the bug in the -DHCP case, it just prints one line and I don't remember how to connect to it. So provide more detail if a problem remains.

**Comment by qiaojingx** [comment]
Verified with commit e720399 . This issue is fixed.
