### ISSUE TITLE
[docs] README.md need to update for building on MacOS

### ISSUE THREAD

**Issue by qiaojingx** [intel/zephyr.js#1714]
### Description

In order to build on MacOS,  README.md need to update according to http://docs.zephyrproject.org/getting_started/installation_mac.html.
 
### Test Code

[README.md](https://github.com/01org/zephyr.js/blob/master/README.md)
 
### Actual Result

Build with `BOARD=frdm_k64f` will fail with error `Kconfig not found` by following instruction [building-and-running-on-macos](https://github.com/01org/zephyr.js/blob/master/README.md#building-and-running-on-macos).
 
<img width="575" alt="screen shot 2017-12-13 at 5 16 57 pm" src="https://user-images.githubusercontent.com/19813546/33931191-3c590012-e02a-11e7-8eeb-cbc27494eac7.png">

### Expected Result

Build with `BOARD=frdm_k64f` succeed.
<img width="577" alt="screen shot 2017-12-13 at 5 20 12 pm" src="https://user-images.githubusercontent.com/19813546/33931208-47a1be32-e02a-11e7-9912-dc492e8c730b.png">
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 1b970c8 | MacOS | Dec 13, 2017 | Fail
 
### Additional Information

execute below commands before build, will fix `Kconfig not found` issue.

Build Kconfig in $ZEPHYR_BASE/build and add it to path
```
$ cd $ZEPHYR_BASE
$ mkdir build && cd build
$ cmake $ZEPHYR_BASE/scripts
$ make
$ echo "export PATH=$PWD/kconfig:\$PATH" >> $HOME/.zephyrrc
$ source $ZEPHYR_BASE/zephyr-env.sh
```

**Comment by jimmy-huang** [comment]
@qiaojingx I've created a patch #1780 to address some of these issues, can you see if anything else needs to be updated?

**Comment by qiaojingx** [comment]
Verified with commit 0c0af9b. README.md has been updated. Close.
