### ISSUE TITLE
[gfx] If 'x0 = x1, y0 > y1' or 'x0 > x1, y0 = y1', that line drawing is different of expectation.

### ISSUE THREAD

**Issue by cuiyanx** [intel/zephyr.js#1743]
### Description

When I test drawLine() function, I find that line drawing is different of expectation if I set 'x0 = x1, y0 > y1' or 'x0 > x1, y0 = y1'. The direction of the line is wrong.
 

### Test Code

Simple test:
```
var LCD = require("ST7735.js");
var board = require("board");
var drawImmediate = board.name === "arduino_101" ? true : false;
var gfxLib = require("gfx");

var GFX = gfxLib.init(LCD.width, LCD.height, LCD.initScreen, LCD.drawCB, drawImmediate, LCD);

var BLACK =  [0x00, 0x00];
var WHITE =  [0xFF, 0xFF];

GFX.fillRect(0, 0, 128, 160, BLACK);

GFX.drawLine(64, 80, 64, 10, WHITE);
GFX.drawLine(64, 80, 10, 80, WHITE);
```

 

### Actual Result

Line1: Starting point： [64, 80], End point： [64, 150]
Line2: Starting point： [64, 80], End point： [118, 80]

### Expected Result

Line1: Starting point： [64, 80], End point： [64, 10]
Line2: Starting point： [64, 80], End point： [10, 80]

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | b17a496b0 | Arduino 101 | Jan 9, 2018 | Fail

**Comment by qiaojingx** [comment]
Verified with commit 8b0ac4d + #1755. This issue is not reproducible.

**Comment by cuiyanx** [comment]
Fixed and closed
