### ISSUE TITLE
[PnP] FRDM_K64F RAM sample increase obviously compared with master commit 8b0ac4d.

### ISSUE THREAD

**Issue by hanyia** [intel/zephyr.js#1781]
Test with ww04 master commit on zephyr board, found frdm_k64f RAM sample has more than 8% gap compared with ww03 commit. SDK version is v0.9.2. Detail info as below table:

Device | KPI | ww04 master:e720399 | ww03 master:8b0ac4d  | ww04 vs ww03
-- | -- | -- | -- | --
FRDM_K64F | Zephyr_Helloworld_RAM(Byte) | 27204 | 25156 | 8.14%

**Comment by jimmy-huang** [comment]
Yes, this was intended due to the fact that we increased the default callstack size from 2k to 4k for all platforms, as we are hitting stability issues with networking.

**Comment by hanyia** [comment]
@jimmy-huang thanks your explanation, let us record this as expectation.
