### ISSUE TITLE
WebSocketServer samples shows two PONG events when there should be one

### ISSUE THREAD

**Issue by grgustaf** [intel/zephyr.js#1787]
Run the WebSocketServer.js sample on K64F at least, then connect with node client. In between the 10 message lines, it shows two PONG prints. There should only be one.

Investigating a little yesterday, it appeared there's only one `tcp_received` call and one `zjs_defer_work` call but somehow it's resulting in two pong events. I wonder if maybe the message isn't getting pulled out of the ring buffer the first time for some reason.

**Comment by brianjjones** [comment]
FWIW the second pong is coming from the client side, which is being run by node - and running their version of WS.  So its quite possible it is a node bug or Zephyr issue.

**Comment by brianjjones** [comment]
Confirmed, Node.js automatically sends a pong in response to a ping.  Having the ws.pong line in there causes two pongs to be sent.  See #1797

@grgustaf should I update our WS code to match this behavior? I assume this would go in after 0.5.
