### ISSUE TITLE
[build] When building with Linux target, I have got some "warning".

### ISSUE THREAD

**Issue by cuiyanx** [intel/zephyr.js#1801]
### Description

When I am building with Linux target, I have got some "warning". Although I can finish the Linux building, but please fix it.
 

### Steps to Reproduction

` make BOARD=linux`

### Actual Result

Warning 1:
`warning: "OC_CLOCK_CONF_TICKS_PER_SECOND" redefined`
 
Warning 2:
`warning: variable ‘key’ set but not used [-Wunused-but-set-variable]`

### Expected Result

No warning.
 

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
:---:|:---:|:---:|:---:|:---:
master | d09e4b36 | Linux | Jan 29, 2018 | Fail

**Comment by grgustaf** [comment]
I don't seem to reproduce this. Can you give more context around the warnings? Are you sure there wasn't more to the build command line?

**Comment by jimmy-huang** [comment]
I do see the warning: variable ‘key’ set but not used [-Wunused-but-set-variable] warning, but i don't see the first one.

**Comment by grgustaf** [comment]
OK I do see that first error in Travis output, so we should be able to address this.

**Comment by jimmy-huang** [comment]
patch submitted #1803

**Comment by cuiyanx** [comment]
I re-test this issue with #1802 and #1803, this issue will be fixed.
Wait for merge #1802 and #1803, I will close this.
