### ISSUE TITLE
The existing file disappears after rebooting or reseting STM32F407G-DISC1 and Olimex STM32-E407 boards

### ISSUE THREAD

**Issue by xiaoyu3x** [intel/zephyr.js#1826]
## Issue description
The existing file disappears after rebooting or reseting STM32F407G-DISC1 and Olimex STM32-E407 boards

## Steps to reproduce
1. Build and flash image into board.
2. Start WebIDE and connect board.
3. Use 'load' command to create file in console.
4. Execute 'reboot' command in console or press 'reset' button on board.

## Actual Result

The existing file disappears, e.g. There are "f.js" and "parse.js", but they disappear after reboot or reset board.
![capture](https://user-images.githubusercontent.com/17694094/35790889-9fb03412-0a7f-11e8-9ee7-add62b7455cc.PNG)

## Expected Result
Files didn't disappeared after reboot or reset board.

## Test Build
Branch| Commit id | Target Device |Test Date | Result 
---| ---| ---| ---|--- 
master | [ede4509](https://github.com/intel/zephyr.js/commit/ede4509d98da5f0187b82a7867fc0277641c4ba7) | STM32F407G-DISC1/Olimex STM32-E407 | Feb 5, 2018 | Fail 
master | [ede4509](https://github.com/intel/zephyr.js/commit/ede4509d98da5f0187b82a7867fc0277641c4ba7) | A101 | Feb 5, 2018 | Pass

**Comment by jimmy-huang** [comment]
This is probably because both the boards do not have a dedicated flash for the filesystem like the A101.  So it's similar to the k64f, where it uses the RAM to simulate the filesystem, therefore it will be gone when you reboot, I don't think we can fix this unless the board can use another filesystem format like SD card support.

**Comment by xiaoyu3x** [comment]
Thanks, @jimmy-huang 

According to your comment, I will close it.
