### ISSUE TITLE
[ashell] Should stm32f4_disco and olimex_stm32_e407 support ashell like ide?

### ISSUE THREAD

**Issue by qiaojingx** [intel/zephyr.js#1844]
### Description

Should stm32f4_disco and olimex_stm32_e407 support ashell since they support ide now?
Build ashell target for these two boards failed.
 
### Steps to Reproduction

1.  `make BOARD=stm32f4_disco ashell`
2.  `make BOARD=olimex_stm32_e407 ashell`

### Actual Result

![selection_072](https://user-images.githubusercontent.com/19813546/36020036-307f8468-0dbc-11e8-8430-ae92d3ef1b84.png)
 
### Expected Result

Build ashell target successfully.

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 0ae1d62| stm32f4_disco | Feb 09, 2019 | Fail
master | 0ae1d62| olimex_stm32_e407 | Feb 09, 2019 | Fail

**Comment by brianjjones** [comment]
Was just missing a change to the CLI json file, I have a fix open to take care of this.

**Comment by qiaojingx** [comment]
Verified with commit 9db8f2b. This issue is fixed.
Close.
