### ISSUE TITLE
Non-blocking BSD sockets not working as expected

### ISSUE THREAD

**Issue by jimmy-huang** [intel/zephyr.js#1848]
There seems to be an issue with sockets blocking on recv() when it is set to non-blocking mode, this is causing the JerryScript debugger to stall as it expects it to return immediately.  I've filed a bug on Zephyr upstream https://github.com/zephyrproject-rtos/zephyr/issues/6309.

@pfalcon, I've created sample code to reproduce the issue on the bug, can you take a look there when you have a chance since you implemented the socket api?

**Comment by pfalcon** [comment]
Will do, thanks!

**Comment by jimmy-huang** [comment]
closing this as it's fixed in Zephyr 1.11
