### ISSUE TITLE
[Console] Console.log cannot print each type correctly

### ISSUE THREAD

**Issue by qiaojingx** [intel/zephyr.js#1858]
### Description

This is a regression issue. Console.log cannot print each type correctly, it causes `Segmentation fault` on Linux & MacOS, causes `BUS FAULT` error on FRDM_K64F, causes incorrect output on arduino101.
 
### Test Code

[Console.js](https://github.com/01org/zephyr.js/blob/master/samples/tests/Console.js);
[test-console-manual.js](https://github.com/01org/zephyr.js/blob/master/tests/test-console-manual.js); 
[Buffer.js](https://github.com/01org/zephyr.js/blob/master/samples/Buffer.js);
[BufferMemory.js](https://github.com/01org/zephyr.js/blob/master/samples/tests/BufferMemory.js);

### Steps to Reproduction

Arduino101:
`1. make JS=samples/tests/Console.js`
`2. make dfu
`
FRDM_K64F:
`1. make BOARD=frdm_k64f JS=samples/tests/Console.js`
`2. cp outdir/frdm_k64f/zephyr/zephyr.bin /media/<username>/MBED/`

Linux & MacOS:
`1. make BOARD=linux`
`2. ./outdir/linux/release/jslinux samples/tests/Console.js`

### Actual Result

1. Arduino101:
![selection_079](https://user-images.githubusercontent.com/19813546/37264579-077518f4-25e9-11e8-9179-6c189b9080a3.png)

2. FRDM_K64F:
![selection_078](https://user-images.githubusercontent.com/19813546/37264573-ff88887e-25e8-11e8-8360-0ea9aa6d2445.png)

3. `Segmentation fault` occurs on Linux:
![selection_076](https://user-images.githubusercontent.com/19813546/37263224-110f2dca-25e2-11e8-8d0e-545b6cdfeb15.png)

4. `Segmentation fault` occurs on MacOS:
![img_2693](https://user-images.githubusercontent.com/19813546/37265862-473d6ace-25f1-11e8-902b-1ec801ca616f.JPG)

### Expected Result

No error.
![selection_080](https://user-images.githubusercontent.com/19813546/37265961-e32fef24-25f1-11e8-9605-df4365678d7c.png)
 
### Test Builds

Branch | Commit Id | Target Device | Test Date | Result
---|---|---|---|---
master | 9db8f2b | Arduino101 & FRDM_K64F & Linux & MacOS | Mar.12, 2018 | Fail
master | e4e4c95| Arduino101 & FRDM_K64F & Linux & MacOS | Mar.12, 2018 | Pass

**Comment by xiaoyu3x** [comment]
This issue is reproduced on STM32F407G-DISC1 and Olimex STM32-E407 with commit [9db8f2b](https://github.com/intel/zephyr.js/commit/9db8f2b5d523b4a09bedf36f6f350ef91b6bae3a)

**Comment by qiaojingx** [comment]
Verified with commit 3d4a43c in master. This issue is fixed.
