### ISSUE TITLE
[BLE] Primary Service UUID not found

### ISSUE THREAD

**Issue by xiaoyu3x** [intel/zephyr.js#1869]
### Description

 This is a regression issue, after zephyr updated to 1.11. Primary Service UUID cannot find. I cannot use nRF app or WebBlueTooth(https://goo.gl/QEvyDZ) to communication with Arduino101.

### Test Code

[BLE.js](https://github.com/intel/zephyr.js/blob/master/samples/BLE.js);
[WebBluetoothDemo.js](https://github.com/intel/zephyr.js/blob/master/samples/WebBluetoothDemo.js);
[WebBluetoothGroveLcdDemo.js](https://github.com/intel/zephyr.js/blob/master/samples/WebBluetoothGroveLcdDemo.js); 
[HeartRateDemo.js](https://github.com/intel/zephyr.js/blob/master/samples/HeartRateDemo.js); 
[SensorBLEDemo.js](https://github.com/intel/zephyr.js/blob/master/samples/SensorBLEDemo.js)
[test-ble.js](https://github.com/intel/zephyr.js/blob/master/tests/test-ble.js)

### Steps to Reproduction

Scenario 1:
1. `make JS=samples/BLE.js ROM=256`
2. `make dfu`
3. connect Arduino101 with nRF app

Scenario 2:
1. `make JS=samples/WebBluetoothDemo.js ROM=256`
2. `make dfu`
3. connect Arduino101 with WebBlueTooth(https://goo.gl/QEvyDZ)

### Actual Result

Scenario 1:
![screenshot_20180411-053901](https://user-images.githubusercontent.com/17694094/38654549-7b8b9f80-3e42-11e8-95f1-72b26e1a6574.png)

Scenario 2:
![screenshot_20180411-043741](https://user-images.githubusercontent.com/17694094/38654526-59151634-3e42-11e8-8ff4-20261e90bbdc.png)

### Expected Result

Scenario 1:
![screenshot_20180411-223605](https://user-images.githubusercontent.com/17694094/38654578-a063e8a8-3e42-11e8-9c1a-76e98237b2bc.png)

Scenario 2:
![screenshot_20180411-230454](https://user-images.githubusercontent.com/17694094/38654585-a51951a8-3e42-11e8-8f75-ef25c7fcfed9.png)

### Test Builds

Branch | Commit Id | Target Device | Test Date | Result | Comment
---|---|---|---|---|---
master | 3f8eb85| Arduino 101 | Apr 11, 2017 | Pass |
master | d5d5540 | Arduino 101 | Apr 11, 2017 | Fail |

**Comment by qiaojingx** [comment]
Verified with commit 2273038. This issue is fixed.
